
services:
  mongodb:
    image: mongo:latest
    container_name: pepperAndHDM
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./database-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: pepper
      MONGO_INITDB_ROOT_PASSWORD: visionlab